# Generated by Django 5.1 on 2024-08-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code4us', '0002_book_category_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category_book',
        ),
    ]
