# Generated by Django 5.1 on 2024-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code4us', '0003_remove_book_category_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kategoriler',
            field=models.ManyToManyField(related_name='books', to='code4us.category'),
        ),
    ]
